### ISSUE TITLE
DeviceError: Observable Prod not supported

### ISSUE THREAD

**Issue by cqc-melf** [CQCL/pytket-pennylane#118]
CI testing shows: `pennylane._device.DeviceError: Observable Prod not supported on device pytket.pytketdevice`

**Comment by cqc-melf** [comment]
See https://github.com/CQCL/pytket-pennylane/pull/117

**Comment by cqc-alec** [comment]
Related: https://github.com/PennyLaneAI/pennylane/issues/5707 .
